sudo: false
language: perl
perl:
  - "5.26"
  - "5.26-shrplib"
  - "5.24"
  - "5.24-shrplib"
  - "5.22"
  - "5.22-shrplib"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
#  - "5.8"
notifications:
  recipients:
    - fusioninventory-commit@lists.alioth.debian.org
  email:
    on_success: change
    on_failure: always
  webhooks: https://hooks.aethonan.pro/travisci/-1001137546384/
# whitelist
branches:
  only:
    - master
    - develop
