branches:
  only:
    - 2.4.x

notifications:
  - provider: Email
    to:
    - fusioninventory-commit@lists.alioth.debian.org
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true
  - provider: Webhook
    url: https://hooks.aethonan.pro/appveyor/-1001137546384/

skip_tags: true
shallow_clone: true

platform:
  - x86
  - x64

# As of 2017/11, lastest strawberryperl based on perl 5.26 is failing on Win32::Daemon
install:
  - cinst strawberryperl --version 5.24.2.1
  - set PATH=C:\strawberry\perl\bin;C:\strawberry\perl\site\bin;C:\strawberry\c\bin;%PATH%
  - cd C:\projects\%APPVEYOR_PROJECT_NAME%
  - echo %cd%
  - cpan -T Module::Install
  - cpanm --notest --installdeps .
  - cpanm --notest Compress::Zlib IO::Socket::SSL LWP::Protocol::https
  - cpanm --notest Win32::Daemon Win32::Unicode::File
  - cpanm --notest Parse::EDID DateTime
  - cpanm --notest Archive::Extract Digest::SHA File::Copy::Recursive
  - cpanm --notest JSON::PP URI::Escape Net::Ping Parallel::ForkManager

build_script:
  - perl Makefile.PL
  - dmake

test_script:
  - dmake test
